fix: improve llm parsing
AIHawk-co/Auto_Jobs_Applier_AI_Agent pull request #806
Opened 2024-11-11 02:20 UTC by 49Simon

Fixes #795
- Force the llm to output the answer only
- Clean markdown output, if any
- This will improve the distance calculation of Levenshtein, when using the `find_best_match` function

2024-11-11 16:43 UTC, surapuramakhil requested changes
I am slightly skeptical about LLM output cleaning. removing # and * from output.

No issue in updating prompts for forcing LLMs.

@49Simon request to have second review by someone who previously contributed to AI aspect to this project.

2024-11-11 16:43 UTC, surapuramakhil commented on src/ai_hawk/llm/llm_manager.py
> +            output = self._clean_llm_output(raw_output)
I would suggest rather than cleanig forcing LLM is better option. (prompt engineering)

2024-11-11 16:43 UTC, surapuramakhil commented on src/ai_hawk/llm/llm_manager.py
> +        output = self._clean_llm_output(raw_output)
I believe sometimes these questions not only be one word answer questions.

something like "why are  you interested in <compnay name>?"

* serve as bullet points

2024-11-11 18:05 UTC, feder-cr commented
I will @surapuramakhil

2024-11-12 04:55 UTC, 49Simon commented
@feder-cr let me know what you think of this. Will tag @cjbbb and @sarob if they've any input on this

2024-11-13 01:36 UTC, feder-cr approved these changes

2024-11-13 01:41 UTC, surapuramakhil approved these changes

2024-11-13 01:41 UTC, merged